on: [push, pull_request]
name: tests
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.14.x"
      - name: Run tests
        run: cd parser && go test -cover ./...
